### PR TITLE
fix(YouTube - Override YouTube Music buttons): Support launching arbitrary third-party music clients

### LINKED ISSUE #957: feat(YouTube): Custom music package name won't open, only YT Morphe package name can open
### Bug description

I try to add Metrolist as default override YouTube music button but it won't work it showing like this 

Image

### App version patched

20.45.36

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by ILoveOpenSourceApplications**
### Description

Closes #957.

### Additional context

Previously, the "Override YouTube Music actions" patch failed to launch custom FOSS clients (like ViMusic, InnerTune, or Metrolist) on Android 11+ due to package visibility rules, and would frequently redirect to a website. This PR fixes that issue.

### Test results

- [x] Tested on both the **minimum** and **maximum** supported versions
- [x] Tested on **experimental** supported versions (Optional)

### CODE REVIEW

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/OverrideYouTubeMusicActionsPatch.java [hunk 1]
```diff
@@ -44,22 +60,41 @@ public static Intent overrideSetData(Intent intent, Uri uri) {
         }
 
         String uriString = uri.toString();
-        if (uriString.contains(YOUTUBE_MUSIC_PACKAGE_NAME)) {
-            if (uriString.startsWith("market://") || uriString.contains("play.google.com/store/apps")) {
+        if (uriString.contains(YOUTUBE_MUSIC_PACKAGE_NAME) ||
+                (uriString.startsWith("market://") && uriString.contains(YOUTUBE_MUSIC_PACKAGE_NAME)) ||
```
Comment (LisoUseInAIKyrios) [inline extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/OverrideYouTubeMusicActionsPatch.java]: `uriString.contains(YOUTUBE_MUSIC_PACKAGE_NAME))` is redundantly checked.

`(uriString.startsWith("market://") && uriString.contains(YOUTUBE_MUSIC_PACKAGE_NAME))` could be `uriString.startsWith("market://")`

**Comment by ILoveOpenSourceApplications** [comment]
I renamed the setting key, is migration needed?

**Comment by LisoUseInAIKyrios** [comment]
Yes. Add a dummy old setting with the old key and do like the other migration settings.
