### PR TITLE
fix(YouTube - Hide Shorts components): Hide Shorts in search nav button

### LINKED ISSUE #744: bug(YouTube): Search in Nav Bar at index 0 breaks Shorts hidden in feed function
Image
Image

### Bug description

Morphe patches 1.17
YouTube 20.44.38

With the latest version of Morphe and the recommended YT app version the hide shorts in home feed is broken, when assigning the nav bar search button to index 0.

If you set those settings accordingly, go back to the home feed, then click on the subs button to reset the menu. Then click on the home feed, which shows no shorts at this point. After that click the search button in the nav bar and then go back by using the android system back key and suddenly the shorts cluster is showing up at the top of the home feed.

If you then click on Subscriptions and then back on feed it is loaded properly without shorts, but when you click on search nav bar and then go back again the shorts are no longer hidden.

I also activated the settings in nav bar.

EDIT: It just occurred to me now to try it, but the exact **same thing happens, when you assign the settings button to index 0.** Tapping it and then going back shows shorts in the home feed despite them been hidden.

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by caglareker**
### Description

Shorts filter wasn't working when search was the active nav button. The issue was the switch statement only had HOME and EXPLORE, so I added SEARCH and SETTINGS to it.

Closes #744

### Additional context

N/A

### Test results

- [x] Tested on both the **minimum** and **maximum** supported versions
- [x] Tested on **experimental** supported versions (Optional)

### CODE REVIEW

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java [hunk 1]
```diff
@@ -546,7 +546,7 @@ private boolean shouldHideShortsFeedItems() {
         }
 
         return switch (selectedNavButton) {
-            case HOME, EXPLORE -> hideHome;
+            case HOME, EXPLORE, SEARCH, SETTINGS -> hideHome;
```
Comment (LisoUseInAIKyrios) [inline extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java]: There is a separate setting to hide Shorts in search. Settings menu can't have any Shorts.


```suggestion
            case HOME, EXPLORE -> hideHome;
            case SEARCH -> hideSearch;
```

**Comment by suLac4ever** [comment]
The same issue happens with the settings button at index 0.

**Comment by LisoUseInAIKyrios** [comment]
Thanks for the help
