### PR TITLE
fix(YouTube): "Restore old setings menu" does not work with experimental app targets

### LINKED ISSUE #1117: bug(YouTube): "Restore old setings menu" does not work with experimental app targets
### Bug description

Forcing old menus shows a broken mix of no icons and bold grey icons.

Problem does not happen with 20.45.36

### App version patched

21.14.482

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by inotia00**
### Description

Closes https://github.com/MorpheApp/morphe-patches/issues/1117.

### Additional context

N/A

### Test results

- [ ] Tested on both the **minimum** and **maximum** supported versions
- [X] Tested on **experimental** supported versions (Optional)

### CODE REVIEW

**Review by LisoUseInAIKyrios — APPROVED** [review]

File: patches/src/main/kotlin/app/morphe/patches/youtube/misc/fix/preference/FixPreferenceIconPatch.kt [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+
+                            # setIcon(null).
+                            const/4 v3, 0x0
+                            invoke-virtual { v2, v3 }, $setPreferenceIconMethodCall
+
+                            goto :loop
+
+                            :exit
+                            return-void
+                        """
```
Comment (inotia00) [inline patches/src/main/kotlin/app/morphe/patches/youtube/misc/fix/preference/FixPreferenceIconPatch.kt:100]: ### FYI

The patch is an implementation for the following simple code:

```
            if (FixPreferenceIconPatch.removePreferenceIcon()) {
                PreferenceScreen mPreferenceScreen = getPreferenceScreen();
                if (mPreferenceScreen != null) {
                    for (int i = 0, prefCount = mPreferenceScreen.getPreferenceCount(); i < prefCount; i++) {
                        Preference mPreference = mPreferenceScreen.getPreference(i);
                        if (mPreference != null) {
                            mPreference.setIcon(null);
                            mPreference.setIconSpaceReserved(false);
                        }
                    }
                }
            }
```

In the unpatched YouTube, `androidx.preference.Preference` is used instead of `android.preference.Preference`, and the `setIcon(Drawable)` and `setIconSpaceReserved(boolean)` methods are obfuscated.

So.. instead of handling this in the extension, process it in the helperMethod.
