### PR TITLE
fix(YouTube - Disable Shorts resuming on startup): Resolve patch not working on experimental versions

### LINKED ISSUE #288: bug(YouTube): Shorts resume even after a cold start with experimental patching of `21.03+`
### Bug description

https://github.com/user-attachments/assets/6de6c9aa-65cd-435f-b8be-98c83535cf63

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by ILoveOpenSourceApplications**
### Description

Closes #288.

### Additional context

N/A

### Test results

- [x] Tested on **experimental** supported versions (Optional)

### CODE REVIEW

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/settings/Settings.java [hunk 1]
```diff
@@ -358,7 +358,7 @@ public class Settings extends SharedYouTubeSettings {
     public static final BooleanSetting WIDE_SEARCHBAR = new BooleanSetting("morphe_wide_searchbar", FALSE, true);
 
     // Shorts
-    public static final BooleanSetting DISABLE_RESUMING_SHORTS_PLAYER = new BooleanSetting("morphe_disable_resuming_shorts_player", FALSE);
+    public static final BooleanSetting DISABLE_SHORTS_RESUMING_ON_STARTUP = new BooleanSetting("morphe_disable_shorts_resuming_on_startup", FALSE);
```
Comment (wchill) [inline extensions/youtube/src/main/java/app/morphe/extension/youtube/settings/Settings.java:361]: Any reason to change the preference name? It should be migrated if so.

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/settings/Settings.java:361]: Nothing much, just matching it with the patch name change.

Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/settings/Settings.java:361]: This is default on (do not resume Shorts), and I don't think many users have changed it.

But it could be a quick two lines of code to migrate data.

File: patches/src/main/resources/addresources/values/youtube/strings.xml [hunk 2]
```diff
@@ -1425,10 +1425,10 @@ If later turned off, it is recommended to clear the app data to prevent UI bugs.
...
     <string name="morphe_change_start_page_always_summary_off">Start page is changed only on app startup</string>
 
-    <!-- layout.startupshortsreset.disableResumingShortsOnStartupPatch -->
-    <string name="morphe_disable_resuming_shorts_player_title">Disable resuming Shorts player</string>
-    <string name="morphe_disable_resuming_shorts_player_summary_on">Shorts player will not resume on app startup</string>
-    <string name="morphe_disable_resuming_shorts_player_summary_off">Shorts player will resume on app startup</string>
+    <!-- layout.shortsnoresume.disableShortsResumingOnStartupPatch -->
+    <string name="morphe_disable_shorts_resuming_on_startup_title">Disable Shorts resuming on startup</string>
+    <string name="morphe_disable_shorts_resuming_on_startup_summary_on">Shorts will not resume on app startup</string>
+    <string name="morphe_disable_shorts_resuming_on_startup_summary_off">Shorts will resume on app startup</string>
```
Comment (LisoUseInAIKyrios) [inline patches/src/main/resources/addresources/values/youtube/strings.xml:1431]: Todo: rename these on Crowdin before merging.

**Comment by LisoUseInAIKyrios** [comment]
It would be useful if a second person can confirm this works. Shorts player doesn't resume for me for unknown reasons.
