### PR TITLE
fix(YouTube - Hide Shorts components): Resolve hiding Shorts also hiding channel page headers

### LINKED ISSUE #207: bug(YouTube): Headers in channel Home tab are hidden when opened in tabs where Shorts shelves are hidden
### Bug description

Opening channel pages where Shorts shelves are hidden also hides section headers in the channel home page
Image

When opening channel pages where Shorts shelves are not hidden, headers appear as it normally would:

Image

Hiding Shorts in watch history also hides the date when it was watched ("Today" should appear below the filter bar):

Image

This bug has existed since ReVanced era; this does not occur on RVX patches.

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by ILoveOpenSourceApplications**
### Description

Closes #207

### Additional context

Adds "Hide in channel page" setting which hides Shorts shelf that appears in the Home tab of the channel page.

### Test results

- [x] Tested on both the **minimum** and **maximum** supported versions
- [x] Tested on **experimental** supported versions (Optional)

### CODE REVIEW

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java [hunk 1]
```diff
@@ -458,9 +463,17 @@ boolean isFiltered(String identifier, String accessibility, String path, byte[]
...
-            if (contentIndex != 0) return false;
+            // Shelf header is used in multiple places (history, channel, etc.)
+            // Shorts shelf header has index 0
+            if (contentIndex != 0) {
+                return false;
+            }
+
+            // Do not hide shelf header in channel page.
+            // Channel page shelf header does not contain the feed conversation context.
+            if (identifier == null || !feedGroup.matches(identifier)) {
```
Comment (LisoUseInAIKyrios) [inline extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java]: Since this is searching for just a single string, it's faster to not use a trie and instead just use  `!identifier.contains(CONVERSATION_CONTEXT_FEED_IDENTIFIER)`

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java]: Okay. Also, with this change the Home feed Shorts header is being left unfiltered. Does that mean this fix no longer works?

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java]: Code snippet from RVX.
```kotlin
        if (contentType == FilterContentType.PATH) {
            if (matchedGroup == compactFeedVideoPath) {
                return hideShelves && compactFeedVideoBuffer.check(buffer).isFiltered();
            } else if (matchedGroup == shelfHeaderPath) {
                // Because the header is used in watch history and possibly other places, check for the index,
                // which is 0 when the shelf header is used for Shorts.
                if (contentIndex != 0) {
                    return false;
                }
                if (!channelProfileShelfHeader.check(buffer).isFiltered()) {
                    return false;
                }
                return !feedGroup.matches(allValue);
            }
        } else if (contentType == FilterContentType.IDENTIFIER) {
            // Feed/search identifier components.
            if (matchedGroup == shelfHeaderIdentifier) {
                // Check ConversationContext to not hide shelf header in channel profile
                // This value does not exist in the shelf header in the channel profile
                if (!feedGroup.matches(allValue)) {
                    return false;
                }
            } else if (matchedGroup == channelProfile) {
                return true;
            }
            return hideShelves;
        }
```

Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java]: Does the shorts component identifier have this substring? If not then the change here won't change anything about that

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java]: image

This is the issue after the change.

Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java]: Try adding a path contains check for the shorts header

**Comment by ILoveOpenSourceApplications** [comment]
With the recent changes there's no longer any leftover in Home feed, but in v21.05.264, when searching there's some components not getting filtered.

image

**Comment by LisoUseInAIKyrios** [comment]
Can either fix those now (if possible), or merge this and make a separate experimental issue for 21+

**Comment by ILoveOpenSourceApplications** [comment]
It's there in v20.40.45 as well. Needs more testing.

**Comment by ILoveOpenSourceApplications** [comment]
Actually it was working fine. The "Latest posts from" part is actually a horizontal shelf leftover. So, now what?
```kotlin
02-13 02:41:17.548  5098  5098 D morphe: LithoFilterPatch: Searching ID: horizontal_shelf.eml-fe|9a8a842539b454ab Path: horizontal_shelf.eml-fe|9a8a842539b454ab|CellType|horizontal_shelf_content.eml-fe|ad84473663ab20f4|ContainerType|ContainerType|shelf_header.eml-fe|6259e37d3390c6dd|modern_type_shelf_header_content.eml-fe|ee8f4f9a9009a36f|ContainerType|ContainerType|ContainerType| BufferStrings: (horizontal_shelf.eml-fe|9a8a842539b454ab*❙theme|b2bfb63a56c37a6b❙333?❙dismiss❙$KEN_BURNS_ANIMATION_TYPE_UNSPECIFIED❙capabilities|34e6cc3ea7faac41❙Latest posts from ECKOSOLDIER❙Latest posts from ECKOSOLDIER❙-post_base_wrapper_slim.eml-fe|c58761c534d0829*❙ECKOSOLDIER❙UCkjxZqW8zRi4rexA3TMvmrA"❙/@ecko❙2 days ago (edited)*❙//yt3.googleusercontent.com/JGNAON8wPmCTQTJWILlhrhGEfxkJEgJgqb43pJFlS4RyNj1A-7sbNUzFHAjyAWqsbCiqb5zQCDE=s68-c-k-c0x00ffffff-no-rj-mo❙ECKOSOLDIER ❙UCkjxZqW8zRi4rexA3TMvmrA"❙/@ecko❙$UgkxVLqmTqipxipNiBMau4KZBLdoELuvo3wWz❙https://yt3.ggpht.com/l8_FRVxcpjciEaIlhMJYPLxa5yhTOniX53nD5wwlNBMS8QAlxru0ZbZBNoIFize1oe6DUQTcHe-aLnU=s288-c-fcrop64=1,38000000c7ffffff-rw-nd-v1❙Image attachment*$❙...Read more❙Minecraft have released 7 Minecraft Marketplace addons this week! ❙Early Reviews:❙Real Mini-Blocks - https://youtu.be/g_hK0Z7Jaxc❙Gadgets - https://youtu.be/mL3Xum90IWU❙Slice Of Life - https://youtu.be/eTuC_movPjE❙We did also get a brand new update, it's 26.0 so make sure you back up your saves before downloading! (working on a video)❙Changelog: https://feedback.minecraft.net/hc/en-...❙g_hK0Z7Jaxc=❙0gcJCR0AztywvtLA❙https://rr5---sn-5np5oxu-jv36.googlevideo.com/initplayback?source=youtube&oeis=1&c=ANDROID&oad=7000&ovd=7000&oaad=11000&oavd=11000&ocs=550&oewis=1&ohct=2&oaf1=1&oputc=1&ofpcc=2&obbl=24576&msp=1&odepv=1&id=83f84ad19ec96b17&ip=111.92.125.231&initcwndbps=1705000&mt=1770928665❙L?]fff?`2h❙OMX.ffmpeg.vp9.decoder❙OMX.google.vp9.decoder❙c2.android.vp9.decoder❙OMX.Intel.sw_vd.vp9❙OMX.MTK.VIDEO.DECODER.SW.VP9❙c2.mtk.sw.vp9.decoder❙OMX.google.av1.decoder❙c2.android.av1.decoder❙OMX.sprd.av1.decoder❙c2.android.av1-dav1d.decoder❙mL3Xum90IWU=❙https://rr6---sn-5np5oxu-jv3z.googlevideo.com/initplayback?source=youtube&oeis=1&c=ANDROID&oad=7000&ovd=7000&oaad=11000&oavd=11000&ocs=550&oewis=1&ohct=2&oaf1=1&oputc=1&ofpcc=2&obbl=24576&msp=1&odepv=1&id=98bdd7ba6f742165&ip=111.92.125.231&initcwndbps=1822500&mt=1770928665❙L?]fff?`2h❙OMX.ffmpeg.vp9.decoder❙OMX.google.vp9.decoder❙c2.android.vp9.decoder❙OMX.Intel.sw_vd.vp9❙OMX.MTK.VIDEO.DECODER.SW.VP9❙c2.mtk.sw.vp9.decoder❙OMX.google.av1.decoder❙c2.android.av1.decoder❙OMX.sprd.av1.decoder❙c2.android.av1-dav1d.decoder❙eTuC_movPjE=❙0gcJCR0AztywvtLA❙https://rr3---sn-5np5oxu-jv3z.googlevideo.com/initplayback?source=youtube&oeis=1&c=ANDROID&oad=7000&ovd=7000&oaad=11000&oavd=11000&ocs=550&oewis=1&ohct=2&oaf1=1&oputc=1&ofpcc=2&obbl=24576&msp=1&odepv=1&id=793b82fe6a2f3e31&ip=111.92.125.231&initcwndbps=1822500&mt=1770928665❙L?]fff?`2h❙OMX.ffmpeg.vp9.decoder❙OMX.google.vp9.decoder❙c2.android.vp9.decoder❙OMX.Intel.sw_vd.vp9❙OMX.MTK.VIDEO.DECODER.SW.VP9❙c2.mtk.sw.vp9.decoder❙OMX.google.av1.decoder❙c2.android.av1.decoder❙OMX.sprd.av1.decoder❙c2.android.av1-dav1d.decoder❙https://www.youtube.com/redirect?event=backstage_event&redir_token=QUFFLUhqbUxjTHdCai1LSi0td0hxektxcEdsRkp1X2xOQXxBQ3Jtc0trSkxySmIxbGdUVGV4WG5UWDZwbWxMTlV3WHJQRkZ6aTlDLUw0dnZ2UkR0OE1rSkg4UWdiM0t6bmRKQjdJRE5GUFo4YnptZlBMc05kNS03NjMzZFJIMG1zTkotVTNXWWtQMXpwQXJLS0RNVGo4LWQ3SQ&q=https%3A%2F%2Ffeedback.minecraft.net%2Fhc%2Fen-us%2Farticles%2F43274629736717-Minecraft-Bedrock-Edition-26-0-Changelog&html_redirect=1❙USER_INTERFACE_THEME_LIGHT❙USER_INTERFACE_THEME_DARK❙USER_INTERFACE_THEME_DARK❙USER_INTERFACE_THEME_LIGHT❙USER_INTERFACE_THEME_LIGHT❙USER_INTERFACE_THEME_DARK❙USER_INTERFACE_THEME_LIGHT❙USER_INTERFACE_THEME_DARK❙USER_INTERFACE_THEME_LIGHT❙USER_INTERFACE_THEME_DARK❙USER_INTERFACE_THEME_LIGHT❙USER_INTERFACE_THEME_DARK❙USER_INTERFACE_THEME_DARK❙USER_INTERFACE_THEME_LIGHT❙USER_INTER
```

**Comment by LisoUseInAIKyrios** [comment]
If everything is as best as it will get, then time to merge?

**Comment by ILoveOpenSourceApplications** [comment]
Sure. But somehow the child component of horizontal_shelf having shelf_header is being unfiltered and I'm confused how did that occur.

**Comment by ILoveOpenSourceApplications** [comment]
This can be merged. The shelf is hidden fine when I tested on my phone. Was acting weird on the emulator.

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java [hunk 2]
```diff
@@ -29,6 +29,7 @@ public final class ShortsFilter extends Filter {
             "reel_action_bar.", // Regular Shorts.
             "reels_player_overlay_layout." // Shorts ads.
     };
+    private static final String CONVERSATION_CONTEXT_FEED_IDENTIFIER = "horizontalCollectionSwipeProtector=null";
```
Comment (inotia00) [inline extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java:32]: This PR is the cause of https://github.com/MorpheApp/morphe-patches/issues/595.

`horizontalCollectionSwipeProtector=null` is not an identifier, path, or buffer.

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java:32]: Huh, I knew the issue was due to my PR. But never thought it was because of this.

Comment (inotia00) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java:32]: Temporarily revert this PR.

I'll fix it when I have time.
