### PR TITLE
fix(YouTube - Hide Shorts components): Resolve "Hide 'Use this sound' button" and "Hide 'Use this template' button" breaking Shorts player

### LINKED ISSUE #741: bug(YouTube): 'Hide 'Use this Sound' button also hides channel bar, subscribe and video name in shorts
### Bug description

As explained in the title, enabling the option hides the channel bar, subscribe and title buttons.

YouTube 20.44.38 (was happening either since 20.31.x or 20.40.x)
patches 1.17.0 (also probably since 1.16-dev.1)

Image

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by ILoveOpenSourceApplications**
### Description

Closes #741 and #825.

### Additional context

N/A

### Test results

- [x] Tested on both the **minimum** and **maximum** supported versions
- [x] Tested on **experimental** supported versions (Optional)

### CODE REVIEW

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java [hunk 1]
```diff
@@ -484,6 +457,11 @@ boolean isFiltered(String identifier, String accessibility, String path, byte[]
                 return false;
             }
 
+            if (matchedGroup == shortsActionButton) {
+                return useButtonsBuffer.check(buffer).isFiltered() && path.startsWith(REEL_PLAYER_OVERLAY_PATH)
+                        && path.startsWith(REEL_METAPANEL_PATH);
```
Comment (LisoUseInAIKyrios) [inline extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/ShortsFilter.java]: Do cheap checks first. Buffer search is always more work than path check.

```
path.startsWith(REEL_PLAYER_OVERLAY_PATH) && path.startsWith(REEL_METAPANEL_PATH) && useButtonsBuffer.check(buffer).isFiltered();
```

**Comment by LisoUseInAIKyrios** [comment]
Please test this well. Post there when you think it's fully fixed.

**Comment by ILoveOpenSourceApplications** [comment]
Yeah, I'm testing each changes. Will mark as ready only when it's fully fixed.

**Comment by ILoveOpenSourceApplications** [comment]
With the last change everything works well, except there is a gap between seekbar and video title when "Use this sound" button is hidden compared to when the Short is opened from history.

<details><summary>Comparison</summary>
<p>

| History shelf | Shorts remixing this video shelf |
|--------|--------|
| Screenshot_20260313_010540_YouTube | Screenshot_20260313_010615_YouTube |


</p>
</details>

**Comment by ILoveOpenSourceApplications** [comment]
I don't know if there's a better way so that the padding or whatever isn't left behind when hiding the button.

**Comment by LisoUseInAIKyrios** [comment]
It only has the extra space when opened under certain conditions? Seems reasonable and the space doesn't look that out of place.

**Comment by ILoveOpenSourceApplications** [comment]
> It only has the extra space when opened under certain conditions? 

Yes, when opening a Short through either "Shorts remixing this video" in video description or when clicking the sound button and then opening any Shirt from their as well.

> Seems reasonable and the space doesn't look that out of place.

It's slightly bigger than normal.

**Comment by LisoUseInAIKyrios** [comment]
That sounds ok.  Is this ready?

**Comment by ILoveOpenSourceApplications** [comment]
Let me do a couple more changes to see if things get better.

**Comment by ILoveOpenSourceApplications** [comment]
Nope, that won't work. I guess till someone complaints about the gap, this fix can be merged to fix the buttons shifting from right side to left side.
