### PR TITLE
fix(YouTube - Hide layout components): Fix "Hide ticket shelf" not working when "Hide horizontal shelves" is off

### LINKED ISSUE #80: bug(YouTube - Hide layout components): Ticket shelf not hidden when Hide horizontal shelves disabled
### Bug description

I tested it with both recommended version 20.37.48 and latest version 20.51.39.
The ticket shelf can be hidden(partially) when a custom filter is used, but this doesn't work when enabled from the settings.

Hide ticket shelf enabled, no custom filter
Image

With `ticket_item.e` custom filter
Image

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by ILoveOpenSourceApplications**
Closes #80.

### CODE REVIEW

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java [hunk 1]
```diff
@@ -365,6 +372,10 @@ boolean isFiltered(String identifier, String accessibility, String path, byte[]
             return false;
         }
 
+        if (matchedGroup == ticketShelf) {
+            return ticketShelfBuffer.check(buffer).isFiltered();
+        }
+
```
Comment (LisoUseInAIKyrios) [inline extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: Does hide horizontal shelves still work when enabled but ticket shelf is off?

`ticketShelf` will match on any horizontal shelf.

I think the fix is if `horizontalShelves` matches, then check if ticket shelf matches and then handle it there.

Untested code wrote from a phone:
```
        if (matchedGroup == horizontalShelves) {
            if (contentIndex != 0) return false;
            if (ticketShelf.check(buffer).isFiltered()) return Settings.HIDE_TICKET_SHELF.get();
            return hideShelves() || playablesBuffer.check(buffer).isFiltered();
        }
```

Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: This same issue may also happen where playables are hidden if hide horizontal shelves is on but hide playables is off.

```
        if (matchedGroup == horizontalShelves) {
            if (contentIndex != 0) return false;
            if (ticketShelf.check(buffer).isFiltered()) return Settings.HIDE_TICKET_SHELF.get();
            if (playablesBuffer.check(buffer).isFiltered()) return Settings.HIDE_PLAYABLES.get(); // TODO remove HIDE_PLAYABLES from playablesBuffer
            return hideShelves();
        }
```

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: I tested this, and no, it doesn't work.

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: Isn't this same as it was before?

Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: The playables hiding issue, yes.

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: I can't test that as I don't have Playables over here.

Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: I think it's fixed? I never see ticket shelves so it's hard for me to test.

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: I search for the artist "Sabrina Carpenter" and play one of her music videos to find the ticket shelf. And I don't think this change will work, as I locally tested it and it didn't work back then when you suggested it initially. I'll test again and let you know.

**Comment by ILoveOpenSourceApplications** [comment]
It's  `Fix ticket shelf not hiding if horizontal shelves is off?`.

**Comment by LisoUseInAIKyrios** [comment]
?

Horizontal shelve should hide all feed/home/search shelves except ticket shelve and playables.

Ticket shelf and playables should only hide if the setting for either is on.

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java (hunk 1 above)
Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: I just noticed this PR removes the existing path filter of `ticket_item.e`.

Does `ticket_item.e` show up anywhere in the path? Or has it changed and now ticket shelf is always in a shelf?

**Comment by ILoveOpenSourceApplications** [comment]
Right now, if "Hide horizontal shelves" is off and "Hide ticket shelf" is on, ticket shelf isn't hidden. But if "Hide horizontal shelves" is on and "Hide ticket shelf" is on, then only ticket shelf is getting hidden.

**Comment by LisoUseInAIKyrios** [comment]
Try again with the last change

**Comment by ILoveOpenSourceApplications** [comment]
Looks good and functional.

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java (hunk 1 above)
Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: What about this? Does `ticket_item.` still appear in the path anywhere?

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: `ticket_item.e` appears in the buffer of `horizontal_shelf.e` and as a path as well.

Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: When it appears as the path, is that not inside a horizontal shelf?

I'm asking if the `ticket_item.e` path filter should be kept. Because this PR removes it.

Comment (ILoveOpenSourceApplications) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: > When it appears as the path, is that not inside a horizontal shelf?

No.

> I'm asking if the `ticket_item.e` path filter should be kept. Because this PR removes it.

I don't think so. Maybe I added it in this PR. But it was used as a buffer only prior to this.

**Comment by OrdinaryPerson0** [comment]
> I just noticed this PR removes the existing path filter of `ticket_item.e`.
> 
> Does `ticket_item.e` show up anywhere in the path? Or has it changed and now ticket shelf is always in a shelf?

@LisoUseInAIKyrios It is actually hides channel concerts list.

Without `ticket_item.e` filter
Screenshot_20260110_013716_app_morphe_android_youtube_MainActivity_edit_160762636891537

With `ticket_item.e` filter
Screenshot_20260110_013807_app_morphe_android_youtube_MainActivity_edit_160745147282950

File: extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java (hunk 1 above)
Comment (LisoUseInAIKyrios) [reply extensions/youtube/src/main/java/app/morphe/extension/youtube/patches/components/LayoutComponentsFilter.java:368]: Ok then this should be fine.

**Comment by LisoUseInAIKyrios** [comment]
Should concert list be shown?
The nav back button is present in that screenshot. If the nav is present then it could ignore hiding the ticket shelf.

Everywhere ticket shelf _should_ be hidden, is the back button ever shown?

**Comment by LisoUseInAIKyrios** [comment]
ok I see what your screenshot shows.

So everything is ok now? Merge?

**Comment by ILoveOpenSourceApplications** [comment]
Maybe you could look into "Hide Subscribe button" and "Hide Info cards" as well in description? That's also in a similar situation, where I had to move `infocards_section.e` around to get `subscribe_button` to be hidden.

**Comment by ILoveOpenSourceApplications** [comment]
> ok I see what your screenshot shows.
> 
> So everything is ok now? Merge?

Yup, this is ready.

**Comment by LisoUseInAIKyrios** [comment]
I only glanced at `infocards_section.e` but it looks different from this situation. Unless I'm looking at it wrong.
